# ==============================================================================
# ALACRITTY THEME: everblush
# ==============================================================================
[colors.primary]
background = "#141b1e"
foreground = "#dadada"

[colors.cursor]
text = "#141b1e"
cursor = "#8ccf7e"

[colors.selection]
text = "#141b1e"
background = "#8ccf7e"

[colors.normal]
black   = "#232a2d"
red     = "#e57474"
green   = "#8ccf7e"
yellow  = "#e5c76b"
blue    = "#67b0e8"
magenta = "#c47fd5"
cyan    = "#6cbfbf"
white   = "#b3b9b8"

[colors.bright]
black   = "#2d3437"
red     = "#ef7e7e"
green   = "#96d988"
yellow  = "#f4d67a"
blue    = "#71baee"
magenta = "#ce89df"
cyan    = "#76c9c9"
white   = "#dadada"
