# ==============================================================================
# KITTY CONFIGURATION (Material 3 Aesthetic)
# ==============================================================================

# Default Shell
shell fish

# Fonts
font_family      Iosevka Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.0

# Window Layout & Padding
window_padding_width 12
confirm_os_window_close 0
background_opacity 0.83
background_blur 20
dynamic_background_opacity yes
hide_window_decorations yes

# Dynamic Background Opacity Keys
map ctrl+shift+m set_background_opacity +0.05
map ctrl+shift+l set_background_opacity -0.05
map ctrl+shift+1 set_background_opacity 1.0
map ctrl+shift+0 set_background_opacity default

# Cursor & Mouse
cursor_shape beam
cursor_blink_interval 0.5
mouse_hide_wait 3.0

# IPC & Live Reload
allow_remote_control yes
listen_on unix:@kitty

# Active Theme
include theme.conf
