# ==============================================================================
# KITTY THEME: everblush
# ==============================================================================
foreground              #dadada
background              #141b1e
selection_foreground    #141b1e
selection_background    #8ccf7e
cursor                  #8ccf7e
cursor_text_color       #141b1e

active_border_color     #8ccf7e
inactive_border_color   #2d3437

# Black
color0 #232a2d
color8 #2d3437

# Red
color1 #e57474
color9 #ef7e7e

# Green
color2 #8ccf7e
color10 #96d988

# Yellow
color3 #e5c76b
color11 #f4d67a

# Blue
color4 #67b0e8
color12 #71baee

# Magenta
color5 #c47fd5
color13 #ce89df

# Cyan
color6 #6cbfbf
color14 #76c9c9

# White
color7 #b3b9b8
color15 #dadada
