general {
    lock_cmd = pidof hyprlock || hyprlock       
    unlock_cmd = notify-send "Session Unlocked" 
    before_sleep_cmd = hyprlock                
    after_sleep_cmd = hyprctl dispatch dpms on   
    ignore_dbus_inhibit = false
    inhibit_sleep = 3                           
}

listener {
    timeout = 595   # 5sec before lock
    on-timeout = brightnessctl -s set 1
    on-resume = brightnessctl -r
}

listener {
    timeout = 3000
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
    on-resume = brightnessctl -rd rgb:kbd_backlight
}

listener {
    timeout = 7200
    on-timeout = hyprlock
}
