// Battery.qml — Minimalist battery indicator matching and-rs style
import QtQuick
import qs.core as C

Item {
    id: root

    implicitWidth: contentRow.implicitWidth
    implicitHeight: C.Style.barHeight

    readonly property bool charging: C.Battery.isCharging
    readonly property real fillLevel: Math.max(0, Math.min(1, C.Battery.percentage / 100))
    
    // Dynamic Matugen Colors from Colors.qml singleton
    readonly property color colorBase: C.Colors.base
    readonly property color colorSurface2: C.Colors.overlay1
    readonly property color colorFg: C.Colors.text
    readonly property color colorSuccess: C.Colors.green
    readonly property color colorDestructive: C.Colors.red
    readonly property color colorWarning: C.Colors.yellow

    // Dynamic fill color matching Matugen palette
    readonly property color fillColor: {
        if (charging) return colorSuccess
        if (C.Battery.percentage < 20) return colorDestructive
        if (C.Battery.percentage < 40) return colorWarning
        return C.Colors.accent // dynamic accent color generated by Matugen
    }

    Row {
        id: contentRow
        anchors.verticalCenter: parent.verticalCenter
        spacing: C.Style.sp.sm

        // Battery shell (pill body + tip on the right)
        Row {
            anchors.verticalCenter: parent.verticalCenter
            spacing: 0

            // Main battery container
            Rectangle {
                id: batteryShell
                anchors.verticalCenter: parent.verticalCenter
                border.color: root.colorSurface2
                border.width: 2
                color: root.colorSurface2
                height: 16
                radius: 4
                width: 25 // Reduced from 28 to 25 for a super compact, snug pill

                // Battery level fill
                Item {
                    anchors.bottom: parent.bottom
                    anchors.left: parent.left
                    anchors.top: parent.top
                    clip: true
                    width: parent.width * fillLevel

                    Rectangle {
                        border.color: root.colorSurface2
                        border.width: 2
                        color: root.fillColor
                        height: batteryShell.height
                        radius: batteryShell.radius
                        width: batteryShell.width
                    }
                }

                // Percentage text inside the battery pill (centered, solid dark theme base)
                Text {
                    anchors.centerIn: parent
                    color: root.colorBase
                    font.family: "sans-serif"
                    font.pixelSize: 10
                    font.weight: Font.Black
                    text: C.Battery.percentage
                }
            }

            // Battery nipple/tip on the right
            Rectangle {
                anchors.verticalCenter: parent.verticalCenter
                bottomRightRadius: 4
                topRightRadius: 4
                color: root.colorSurface2
                height: (batteryShell.height - (batteryShell.border.width / 2)) / 2
                width: 2.5
            }
        }

        // Charging bolt icon on the right
        Text {
            visible: charging
            anchors.verticalCenter: parent.verticalCenter
            anchors.verticalCenterOffset: 0.5
            text: "power"
            font.family: C.Style.fontIcon
            font.pixelSize: C.Style.icon.xs - 1
            color: root.colorSuccess
        }
    }

    MouseArea {
        anchors.fill: parent
        cursorShape: Qt.PointingHandCursor
        onClicked: C.ShellState.toggleBatteryPicker()
    }
}
