# ░▒▓█ AUTOSTART █▓▒░ #

exec-once = xwaylandvideobridge                                                 # XWayland compatibility bridge
exec-once = wl-paste -p --watch wl-copy -pc                                     # Clipboard management
exec-once = systemctl --user start hyprpolkitagent                              # PolicyKit agent
exec-once = hyprctl setcursor BreezeX-RoséPine 24
exec-once = swww-daemon                                                         # Wallpaper engine
exec-once = hypridle                                                            # Idle manager (config: ~/.config/hypr/hypridle.conf)
exec-once = hyprpanel                                                           # System panel/dock
exec-once = legion-kb-rgb set -e Static -c 30,30,30,30,30,30,30,30,30,30,30,30
exec-once = /usr/bin/pypr
exec-once = /usr/lib/kdeconnectd&!
exec-once = /usr/bin/indicator-kdeconnect&!

