# ░▒▓█ VARIABLES █▓▒░ #

$mainMod =ALT# Main modifier (SUPER=Windows-key, ALT=Alt-key)

$terminal      = kitty
$menu          = rofi -show drun
$notes         = obsidian --disable-gpu
$exit          = hyprctl dispatch exit 
$browser       = firefox



