# Dynamic Theme: Everblush
rootcolor=0x141b1eff
bordercolor=0x323b3eff
focuscolor=0x8ccf7eff
splitcolor=0xe57474ff
dropcolor=0x8ccf7e55
urgentcolor=0xe57474ff
maximizescreencolor=0x8ccf7eff
scratchpadcolor=0x6cbfbfff
globalcolor=0xe5c76bff
overlaycolor=0x6cbfbfff
shadowscolor=0x00000088
